gas = 1000000
gas_prices = "0.025uojo"

[account]
address = "ojo1kjqcup59v5jtlykewz90em6v0cz7tqpd7u7nyr"
chain_id = "agamotto"

[keyring]
backend = "test"
dir = "/Users/username/.ojo"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[relayer]
# "heartbeat" interval for the relayer
interval = "24h"
# deviation expressed as a percentage
# e.g., 0.01 means 1%
deviation = "0.05"
destination = "Arbitrum"
contract = "0x001"

# These are the assets we want to periodically push:
[[assets]]
denom = "BTC"
[[assets]]
denom = "ETH"

# This struct is used to estimate the gas prices to pay axelar
[axelar_gas]
denom = "ibc/xyz"
multiplier = "1.2"
default = "1000000"
