name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  test-unit-contract:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            contracts/*
            test/*

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install packages
        run: |
          yarn install

      - name: Test Contracts
        if: env.GIT_DIFF
        run: |
          make test-unit
